name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          unzip -q MORRE_Flutter_Android_Ready.zip -d extracted
          echo "PROJECT_DIR=extracted/MORRE_Flutter_Android_Ready" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Get packages
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter pub get

      - name: Build APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MORRE-APK
          path: extracted/MORRE_Flutter_Android_Ready/build/app/outputs/flutter-apk/app-debug.apk
